### ISSUE TITLE
recaptcha: unknown injection: 'service:script'

### ISSUE THREAD

**Issue by jamesarosen** [onehilltech/ember-cli-google#7]
[`service:g-recaptcha`](https://github.com/onehilltech/ember-cli-google/blob/f37cc545f12357f7b90fd682fcf471ca76de19f5/packages/ember-cli-google-recaptcha/addon/services/g-recaptcha.js) [depends on](https://github.com/onehilltech/ember-cli-google/blob/f37cc545f12357f7b90fd682fcf471ca76de19f5/packages/ember-cli-google-recaptcha/addon/services/g-recaptcha.js#L71-L72) a `service:script`, but nothing in the package or its dependencies defines that service. Where does it come from?

I'm getting

```
           Error: Assertion Failed: Attempting to inject an unknown injection: 'service:script'
                at assert (http://localhost:4211/auth/assets/vendor.js:50029:15)
                at proto.validateInjections (http://localhost:4211/auth/assets/vendor.js:19637:62)
                at FactoryManager.create (http://localhost:4211/auth/assets/vendor.js:19139:35)
                at Proxy.create (http://localhost:4211/auth/assets/vendor.js:18928:20)
                at instantiateFactory (http://localhost:4211/auth/assets/vendor.js:19002:71)
                at lookup (http://localhost:4211/auth/assets/vendor.js:18949:12)
                at Container.lookup (http://localhost:4211/auth/assets/vendor.js:18837:14)
                at Class.lookup (http://localhost:4211/auth/assets/vendor.js:42190:33)
                at GRecaptchaInvisibleComponent.getInjection (http://localhost:4211/auth/assets/vendor.js:32646:20)
                at http://localhost:4211/auth/assets/vendor.js:30975:25
```

**Comment by jamesarosen** [comment]
Ah, I see. https://github.com/onehilltech/ember-cli-google/commit/78762700b585e28186548aeef11d7659cd1c755f switched to using `ember-cli-script`. The problem is that it's declared in `devDependencies` and in the blueprint, so client applications that are upgrading won't know to install it.

It might help to add it to `peerDependencies` so app authors get a warning about a missing peer dependency when they install.

**Comment by hilljh82** [comment]
@jamesarosen The `ember-cli-script` should have been installed when you installed the `ember-cli-google-recaptcha` add-on since it is listed in its blueprint.

**Comment by jamesarosen** [comment]
I think the problem is that we already had an earlier version of `ember-cli-google-recaptcha`, so it wasn't a fresh install; it was an upgrade.
